### ISSUE TITLE
Raspberry Pi 4 not transmitting 

### ISSUE THREAD

**Issue by RayRaytheGrape** [miegl/PiFmAdv#100]
When I type pifm into the terminal and choose all of my transmission settings I get the error “sudo: ./pifm: command not found” Reinstalling did not help. I am using 32-bit Raspbian.

**Comment by Cheerstoast** [comment]
I use 64 bit, and I successfully get a ~20 meter radius on 88.0khz and a 10cm jumper wire, with software: [markondej/fm_transmitter](https://github.com/markondej/fm_transmitter)

**Comment by Mabbs** [comment]
> I use 64 bit, and I successfully get a ~20 meter radius on 88.0khz and a 10cm jumper wire, with software: [markondej/fm_transmitter](https://github.com/markondej/fm_transmitter)

The software you mentioned does not have stereo sound
