### ISSUE TITLE
Pifm zero

### ISSUE THREAD

**Issue by preterive** [Miegl/PiFmAdv#11]
Hi,
is it working on a pi zero?

**Comment by Miegl** [comment]
Haven't tested, but it should. If something goes wrong share your feedback please. Thanks.

**Comment by Stealthbird97** [comment]
I've been trying to get this to work on Pi Zero W. The program seems to work, unfortunately, the Pi doesn't like something. It will transmit, however, the Pi basically becomes unresponsive afterwards. The WiFi dies, the camera doesn't respond etc.

**Comment by anducampu** [comment]
I have the same problem exactly on pi 0w. However on pi 3b works fine.

**Comment by arhico** [comment]
Have the same problem on my zero W. Commented out gpio 34 release to get it to work ok.

**Comment by mrphax0r** [comment]
It works, tho with minor stuttering.

**Comment by mrphax0r** [comment]
I suspect that it overheats since I applied a heat sink
