### ISSUE TITLE
Audio playing slowy and overrun.

### ISSUE THREAD

**Issue by Niall7459** [Miegl/PiFmAdv#17]
I cna hear the audio playing slowly and I get overruns about 10 secs after starting PiFmAdv.

Starting to transmit on 107.9 MHz.
overrun!!! (at least 54.438 ms long)
overrun!!! (at least 29.159 ms long)

My command:

```
#!/bin/bash
cd /home/pi/PiFmAdv/src

while :; do
        sudo arecord -fS16_LE -r 44100 -D hw:Loopback,1,0 -c 2 - | sudo ./pi_fm_adv -ps "Niall FM" -ctl rds_ctl -audio -
	sleep 2s
	echo "restart"	
done
```

**Comment by Niall7459** [comment]
Overrun is made my Arecord. So maybe PiFmAdv is not reading from STDIN at correct speed.

**Comment by Miegl** [comment]
Closed as it has been resolved + it is not PiFmAdv problem.
