### ISSUE TITLE
not running anymore und pi 1b

### ISSUE THREAD

**Issue by preterive** [Miegl/PiFmAdv#21]
Hello,
i get "WARNING: Frequency should be in megahertz between 76.0 and 108.0, but is 0.000000 MHz
".
i have set all parameters. in an older versions it runs

**Comment by Miegl** [comment]
What did you set as a parameter to -freq ?

**Comment by preterive** [comment]
i have found the problem... i have to set -- and no longer only "-" .

**Comment by Miegl** [comment]
Yeah. Ive switched to getopt.
