### ISSUE TITLE
Make the CLI parameters PiFmRds compliant 

### ISSUE THREAD

**Issue by morrolinux** [Miegl/PiFmAdv#25]
Not really an issue, but it would would be really useful to have the same syntax on both this and the "classic" version, as I could implement both versions in mpradio just by letting the user change the executable path

**Comment by Miegl** [comment]
The PiFmRds parameters are messy and not consistent with ISO POSIX. But I will try my best to make PiFmAdv a fully working replacement of PiFmRds.

**Comment by morrolinux** [comment]
Yea, you're right, don't worry I've figured it out and made it possible to switch anyway :)
