### ISSUE TITLE
Make the process quit on broken pipe / EOF

### ISSUE THREAD

**Issue by morrolinux** [Miegl/PiFmAdv#26]
When piping musing into pi_fm_adv like this
`sox somefile.mp3 -t wav - | pi_fm_adv ...`
It would be nice if upon sox termination pi_fm_adv could terminate as well, just like pi_fm_rds did.
Could you please point me out a way to do so or implement it as I really need this behaviour 
Thank you for this brilliant implementation, thought

**Comment by Miegl** [comment]
Fixed

**Comment by Miegl** [comment]
So I made an option for this. The behaviour you need is not enabled by default, but you can easily turn off the waiting now with `--wait 0`

**Comment by Miegl** [comment]
The waiting is enabled by default because it's better for use with something like LibreTime/AirTime.
