### ISSUE TITLE
dynamic Radio data system RT causes messages to get merged

### ISSUE THREAD

**Issue by Niall7459** [Miegl/PiFmAdv#27]
My radio station changes RT every 10 seconds, with two messages one saying "Welcome to Niall FM Witley" and the other is "Now Playing: " with the song title...

Problem is that its very likely (e.g 80%) of the time to get the messages mixed up...

"Welcome to NiaNow Playing:"
or "Now Playing: Dr Dre feat SnooFM Witley."

![screen shot 2018-04-24 at 10 18 41](https://user-images.githubusercontent.com/9781846/39178125-e1a4766a-47a8-11e8-82af-2446d2f5f5e6.png)
(The radio scrolls the text)

So of course in this picture it has cut in with the second rt "Witley" has been cut off and then the now playing Rt has been inserted.

As if the RT is being transmitted then changed it continues at the same character position but with a different text.

It would be nice if this could be fixed. Im sure it wasnt in PiFMRds in 2016 not sure tho.
![screen shot 2018-04-24 at 10 17 32](https://user-images.githubusercontent.com/9781846/39178227-1a697df6-47a9-11e8-8910-aae3affac371.png)
The script fetches the now playing from a server.

**Comment by Miegl** [comment]
That's due to the AB flag not being changed when updating your RT. If you change the AB flag everytime you update your RT the reciever will (hopefully) clear out the previous text.

just do `echo "AB ON" > rds_ctl` or `echo "AB OFF" > rds_ctl`
you need to change the bit (from ON to OFF) everytime your RT updates!
Let me know if it works!

**Comment by Niall7459** [comment]
Alright i will test it now..

**Comment by Miegl** [comment]
before, it should happen at the same time

**Comment by Niall7459** [comment]
It is still doing that unfortunately. The script I have now is this:
![screen shot 2018-04-24 at 16 04 03](https://user-images.githubusercontent.com/9781846/39196061-211e1d5c-47d9-11e8-974f-4991aeb81544.png)

**Comment by Niall7459** [comment]
Ah wait I need to set "AB ON" and "AB OFF" before RT flag?

**Comment by Niall7459** [comment]
Still no luck with that.

**Comment by Niall7459** [comment]
Ok this is confusing should it be sequenced as such:

1. 
AB ON
RT text
2.
AB ON
AB OFF
RT text
3. 
AB ON
RT text
AB OFF
AB ON
RT text
..

**Comment by Miegl** [comment]
Closing as this should be working. Just switch AB bit everytime you make changes to RT to clear out the text.
