### ISSUE TITLE
termination issue with no audio

### ISSUE THREAD

**Issue by morrolinux** [Miegl/PiFmAdv#28]
What I'm doing: `sox someinput | pi_fm_adv ... --wait 0` 
I don't really understand why, but when sox playback finishes, the shell hangs indefinitely, there is no CTRL+C / CTRL+Z response, and killing -9 pi_fm_adv process seem to have no effect! the pid won't die, although the shell is working... 

PS: I'm on a Pi3 (the only device I seem to have managed to get working with)

**Comment by Miegl** [comment]
I think this is related to the i/o issue. So once that will be fixed (idk how and when) this should work.

**Comment by morrolinux** [comment]
Damn! you're probably right.

**Comment by Miegl** [comment]
With the current state of the raspberry pi firmware the only thing I can do now is trial and error. Don't know how long that will take though and theres a big possibility the firmware will break it anyway.

**Comment by Niall7459** [comment]
I find that the previous way of modulating the wave before PLLC is more reliable. Although it would be great for the PLLC to work. And even then I think the DMA engine should be changed as that solved my problem for the GUI freezing

**Comment by morrolinux** [comment]
@Niall7459 could you be a bit more specific about the "DMA engine change" stuff?

**Comment by Miegl** [comment]
@Niall7459 yes it is. But it's also not very usable quality wise.
I've actually changed the DMA channel from 5 to 14 so I guess it can't be a problem now

**Comment by Miegl** [comment]
So I just pushed https://github.com/Miegl/PiFmAdv/commit/c9a50abfe046d2fafab73623610c8785fc8ed002

Let me know if it works this time @Niall7459 @morrolinux (test on multiple pis with multiple systems please :)

**Comment by Miegl** [comment]
The main point is to get it working on latest firmware, so if it doesn't work on older one it's not a problem

**Comment by morrolinux** [comment]
Good News!
Termination works correctly on both my Pi1 and the Pi3 
As for the stability, I'll test further tomorrow

**Comment by Niall7459** [comment]
@morrolinux The general crash time is 2-4 hours after the program has started, I cannot test at this moment in time.

**Comment by Niall7459** [comment]
@morrolinux @Miegl I can do some tests for like 24 hours etc in a couple of days. and il get back to you with the results.
