### ISSUE TITLE
Less signal strength?

### ISSUE THREAD

**Issue by Niall7459** [Miegl/PiFmAdv#3]
It appears that the signal strength lower than PiFmRds
I used to be able to hear a few hundread meters away but now only like 50 meter with PiFmAdv

**Comment by Miegl** [comment]
Can you try adjusting the deviation with `-dev` ?

**Comment by Niall7459** [comment]
what do I put for -dev

**Comment by Niall7459** [comment]
I set deviation to 25. What was it originally.

**Comment by Niall7459** [comment]
I caanot test until we go in the car.

**Comment by Miegl** [comment]
Its pretty weird that you got so bad signal compared to PiFmRds. I didn't change anything that could reduce signal that much. What RaspberryPi are you using?

**Comment by Niall7459** [comment]
RPi 2

Its fixed, I changed frequency and -dev

reaches same amount if not further.

If i set -dev higher will this boost the range even more

**Comment by Miegl** [comment]
Ok, glad its sorted out. Closing.

**Comment by Miegl** [comment]
So, in addition to this; I went outside (lol) and tested the range of PiFmRds and PiFmAdv. Parameters were at their defaults.
And... the range its pretty much the same.
The deviation is set to 75 kHz as it is standard, and also to be able to fit in my country's limitations.

**Comment by Niall7459** [comment]
? So if I CHANGE the Deviation

IT COULD GO FURTHER?

**Comment by Niall7459** [comment]
????
Please reply @Miegl 

If increase deviation will go further.
I expect not.

**Comment by Miegl** [comment]
Well basically yes. But you can expect the audio quality to be worse.

**Comment by Niall7459** [comment]
At default deviation full bars
At 100 deviation is full bars
at 280 Deviation is 4/10 bars.

What sort of increase can i expect by increasing deviation?
cntermetres meters KILOmeters?

**Comment by Miegl** [comment]
Well deviation != distance.
Deviation is basically bandwidth. Thats why low amount of deviation will result in less distance. And hude amount of deviation isnt good too.

I personally recommend setting the deviation 50 - 75 kHz. I would nener set the deviation to more than 125 kHz.

And of course this will not result in kilometer increase. I don't know what antenna are you using, but Raspberry Pi itself generates very very low signal.

**Comment by Niall7459** [comment]
Meters increase

**Comment by Niall7459** [comment]
My -dev is currently 150 full bars on the radio a few metres away, quality is noticably worse.

**Comment by Niall7459** [comment]
Does deviation at like 300, this wouldnt effect RDS would it??? Make the RDS less strength?

At my freinds house on his radio IT can pick up the RDS but sound is static.

**Comment by Miegl** [comment]
Yeah. All the stuff that gets modulated (mono sound + stereo + pilot tone + rds) is also affected by deviation. So as I said; its better to set deviation at cca. 70kHz and use better antenna, which will affect the distance the most.

**Comment by Niall7459** [comment]
@Miegl . I have my antenna as peice of wire in upstairs of my house, how to build better antenna.

**Comment by Miegl** [comment]
@Niall7459 google it maybe?
