### ISSUE TITLE
Alternative frequencies not working

### ISSUE THREAD

**Issue by tehtafara0-new** [Miegl/PiFmAdv#31]
Using --af doesn't work with the Raspberry Pi 2 B

**Comment by CodingSlime** [comment]
I'm also facing the same issue

**Comment by Miegl** [comment]
`--af 107.9` should work just fine? I don't know, last time I checked it worked fine. I've tried it with both RDS Spy and gr-rds.

**Comment by Miegl** [comment]
Closing. It's working perfectly.
![AF](https://i.imgur.com/00Ihtwj.png)
