### ISSUE TITLE
rds switch parameter problem

### ISSUE THREAD

**Issue by wlmqljj** [Miegl/PiFmAdv#34]
![Image](https://storage.googleapis.com/wlmqljj01.appspot.com/1%20(2).png)

```
[root@alarmpi fm]# ./pi_fm_adv --rds 0
Carrier: 107.90 Mhz, VCO: 971.1 MHz, Multiplier: 50.578125, Divider: 9
Allocating physical memory: size = 4354048, mem_ref = 5, bus_addr = fd6c8000, virt_addr = 0x76771000
Master PLLA Locked
PPM correction is 0.0000, divider is 2129.6052 (2129 + 2479*2^-12).
RDS Options:
RDS: 0
Starting to transmit on 107.9 MHz.
```
the parameter rds 0 results in irregular signal transmitting.
thanks for your program !

**Comment by Miegl** [comment]
Fixed in https://github.com/Miegl/PiFmAdv/commit/6659ac5fa2e7850473c14d6e07034e271ae1524f
Thanks for reporting.
