### ISSUE TITLE
New GPIO function crashes Pi

### ISSUE THREAD

**Issue by Brandon4466** [Miegl/PiFmAdv#36]
Hey there, the new feature that you just added, adding a flag to change what GPIO pin it is broadcasted on, when I run the program without the flag, it works like normal, but when I use
```
--gpio 20
```
It freezes the entire SSH session and after I force close it, it will not let me reconnect until I unplug the pi and plug it back in.

Any ideas?

**Comment by Miegl** [comment]
Weird, for me it works just fine.
Does setting gpio to 32 and 34 cause problems too?
I'm running on the latest kernel & firmware and it just works...
