### ISSUE TITLE
3.5mm jack output

### ISSUE THREAD

**Issue by ssamjh** [Miegl/PiFmAdv#38]
Hey there,

I was wondering if it's possible to output the audio to the 3.5mm jack so I can connect it to my own transmitter?

**Comment by Miegl** [comment]
No, it's not.
But theoretically the program could be changed to do just that.
But remember, your sound card needs capable of outputting at least 192kHz for RDS or 96kHz for stereo.
Take a look at https://github.com/jontio/JMPX.

**Comment by Niall7459** [comment]
And you would need to make sure the transmitter doesn’t have a low-pass filter as this will filter out the RDS signals
