### ISSUE TITLE
Add TP (Traffic Programme) FLAG

### ISSUE THREAD

**Issue by Niall7459** [Miegl/PiFmAdv#4]
Hi.

Please add the TP flag so I can use it with TA.

Mwahaha, THEY WILL BE FORCED TO LISTEN TO MY RADIO.

... If they have TP enabled in the car of course.

**Comment by Miegl** [comment]
TP flag is turned ON by default. Thats why TA works - if TP would be OFF and TA on, the reciever will witch to EON freq.

**Comment by Niall7459** [comment]
cool dude
