### ISSUE TITLE
Using GPIO 34 on Pi 3, 3B+ and Zero W interferences with wifi

### ISSUE THREAD

**Issue by caraiz** [Miegl/PiFmAdv#41]
Hi,

im testing it with a Raspberry Pi 3 and 3B+, the radio works but when the program exits it brokes the network connections.
The wifi is still connected, but ping, ssh,... do not work anymore.

I have debugging a bit and it hangs at **terminate** function _"Set GPIOs to be an output (instead of ALT FUNC 0, which is the clock)."_

Trying with an older version, works fine at Pi 3, but at Pi3B+ occurs the same at code _"Switch EMMC over to PLLD"_

Thanks.

**Comment by Miegl** [comment]
This is weird... Don't know if it's specific to pi 3 or if it's due to firmware updates. Can somebody test this on a raspi 2?

**Comment by caraiz** [comment]
Hi, 

i found that the problem appears executing this line at terminate function:

gpio_reg[3] = (gpio_reg[3] & ~(7 << 12)) | (1 << 12); //GPIO34

Im using default gpio (4).

**Comment by arhico** [comment]
Have the same problem on my zero W. Commented out gpio 34 release to get it to work ok.

**Comment by Miegl** [comment]
Hm, weird. Works fine on my Pi 2. Maybe it has something to do with wifi?

**Comment by Miegl** [comment]
GPIO 34 is in fact used by the SDIO interface, which is used for wifi. https://github.com/raspberrypi/linux/blob/rpi-4.14.y/arch/arm/boot/dts/bcm2710-rpi-3-b.dts#L48

**Comment by Miegl** [comment]
I will update the README to warn about GPIO usage and improve the terminate function to set only the used GPIO.
