### ISSUE TITLE
stopping PiFmAdv in Python3

### ISSUE THREAD

**Issue by klint-k** [Miegl/PiFmAdv#45]
I would like to run PiFmAdv under python3. What I am concerned about is the KeyboardInterrupt may not shut it down.
Is there a python3 "import"?

ps. I do not know how to add help wanted.

**Comment by Miegl** [comment]
Hi,
there's no python script but you can make one yourself.
Take a look at the python script from pifm https://github.com/rm-hull/pifm/blob/master/PiFm.py
