### ISSUE TITLE
no transmit signal but nevertheless console indicate opposite 

### ISSUE THREAD

**Issue by mirovami** [miegl/PiFmAdv#47]
No transmit signal but nevertheless console indicate opposite (it indicates startng to transmit on xx.x mhz) when use a sox source audio.
If i only use ./pi_fm_adb command, the transmision is ok.
EDIT: This issue happens to me with the example file of the tutorial "http://www.linuxvoice.com/episodes/lv_s02e01.mp3"
With PiFmRds it works correctly.

**Comment by Miegl** [comment]
Never happened to me. Does it work with a normal audio file?

**Comment by mirovami** [comment]
yes... if put --audio command with wav audiofile, signal transmit 1 second and then disconect, but only insert ./pi_fm_adv command signal continue transmitting
