### ISSUE TITLE
Send raspberry audio to the station

### ISSUE THREAD

**Issue by SuperFurryTheAwesome** [miegl/PiFmAdv#53]
Hai i am kinda new in raspberry world 
soo i wanted to send raspberry audio system to the station since it can be easier for me to send audio instead of writing the code all the time so how can i do it? i am using raspbian

**Comment by miegl** [comment]
```
pacmd load-module module-pipe-sink file=/tmp/pulse.fifo
pacmd list-sinks  # search your default sink
pacmd load-module module-combine-sink slaves=yoursink,fifo_output
pacmd set-default-sink combined
```
And then run `pi_fm_adv - < /tmp/pulse.fifo`

Let me know if this works.

**Comment by miegl** [comment]
Or with `parec`.
