### ISSUE TITLE
Fatal Error: sndfile.h: does not exist?

### ISSUE THREAD

**Issue by SuperFurryTheAwesome** [miegl/PiFmAdv#54]
Hi so i was installing the program on a raspberry pi 1 b+ with the last raspbian and overclocked but when i put the "make" command it outputs this 
![2019-06-08-082802_1024x768_scrot](https://user-images.githubusercontent.com/51496554/59148218-7bce6100-89cb-11e9-8e7f-c12e37afec3f.png)

i dont think having raspbian in soanish affects the program

**Comment by miegl** [comment]
Please read the README next time, thanks.
https://github.com/miegl/PiFmAdv#how-to-use-it
