### ISSUE TITLE
PI2 Freezes when running PiFmAdv.

### ISSUE THREAD

**Issue by Xeddius** [miegl/PiFmAdv#57]
Followed all instructions, using latest version of raspbian, pi2 freezes and never recovers and must be power-cycled. Nothing is transmitted.

**Comment by miegl** [comment]
are you running a graphical environment? I am running my pi headless all the time, so not sure if it works.

**Comment by Xeddius** [comment]
Yes, it's the default Raspbian with the desktop.

**Comment by miegl** [comment]
Please try running it without a graphical environment to confirm this issue is GUI related.

**Comment by Xeddius** [comment]
My pi boots into a graphical interface by default and I do not have spare SD cards to test with at the moment. I will let you know as soon as I can get another SD card.
