### ISSUE TITLE
I have question about the "WAVE BAND"

### ISSUE THREAD

**Issue by Niall7459** [Miegl/PiFmAdv#6]
Im bit confused is Medium Wave ONLY AM
or is Medium Wave can be FM AS WELL ????

Because if so I want to broadcast Medium Wave FM Make more further pleas.

**Comment by Miegl** [comment]
Of cource, technically you can. But it really doesn't make any sense - am receiver can't really decode fm signal. For that, your fm receiver has to be working on your medium wave freq. Also, there's not much space for fm signal in am spectrum.
