### ISSUE TITLE
Higher CPU usage with doubles

### ISSUE THREAD

**Issue by Anthony96922** [miegl/PiFmAdv#62]
Usage of double over float leads to higher CPU usage. Using the stereo_44100.wav file, top showed 63% total CPU usage. When I replaced all occurrences of double with float and recompiled, top showed 55% usage with the same audio. This test was done on a Raspberry Pi 1.

**Comment by miegl** [comment]
Yep I know, I plan on improving this mess but I don't have time now. Will keep the issue open to track other possible improvents.

**Comment by Anthony96922** [comment]
I'll clean up the code on my fork. Hopefully I can do other stuff to make it run more efficiently.
