### ISSUE TITLE
Still problems with the Pi4

### ISSUE THREAD

**Issue by cpnetserver** [miegl/PiFmAdv#63]
Hi guys,
as soon as the program is launched the system hangs.

# ./pi_fm_adv --freq 100.0 --audio test.wav

[system completely blocked]

**Comment by miegl** [comment]
Probably not Pi4 related. Please try running your RPI headless (without GUI). Disable the DM raspbian uses and run pifmadv through a tty or ssh.

**Comment by cpnetserver** [comment]
Solved! The problem was the GUI.
Thank You Miegl and Thanks to broken2048.

**Comment by miegl** [comment]
Thanks for confirming. Will see what I can do to make it work alongside graphical environment without using PLLD for modulation.
