### ISSUE TITLE
Problem with Streaming

### ISSUE THREAD

**Issue by hlzmeister** [miegl/PiFmAdv#65]
hi, 
i have a problem with sox...if i use Pi_Fm_Rds sox work, but if i use Pi_Fm_Adv the program start but don't trasmitted anything.
i have tried this link http://stream.srg-ssr.ch/m/rsp/mp3_128 too , but nothing!
i need use Pi_Fm_Adv because has many options.
How can i fix it?
thanks.

**Comment by broken2048** [comment]
If you need to pipe that stream to pi_fm_adv, and sox isn't required, this may be the easiest way. 
_sudo mpg123 --stdout http://stream.srg-ssr.ch/m/rsp/mp3_128 | sudo ./pi_fm_adv --srate 44100 --nochan 2 --freq 100.5 --audio -_

**Comment by miegl** [comment]
Closing, open a new issue if needed.
