### ISSUE TITLE
Routing RPi2 audio output to --audio

### ISSUE THREAD

**Issue by mfsoftworks** [miegl/PiFmAdv#68]
Is it possible to route a RPi 2 audio output to --audio for use with Mopidy or the like? Routing the audio output either directly to --audio or to some kind of temp file read by --audio would be good for curating a playlist remotely and broadcasting centrally

**Comment by mfsoftworks** [comment]
It seems like `rec -d -t raw -t wav -r 44100 -c 2 - | sudo ./pi_fm_adv --audio - --ps NygmaRadio --freq 103.9 --tp 0 --power 7` might be the answer but I don't currently have any wire for the RPi to test so I'll check after I have some

**Comment by miegl** [comment]
On Tue, Dec 31, 2019 at 09:26:31AM -0800, MF Softworks wrote:
> `rec -d -t raw -t wav -r 44100 -c 2 - | sudo ./pi_fm_adv --audio - --ps NygmaRadio --freq 103.9 --tp 0 --power 7`

Please note that the program service name (ps) can carry only 8 characters.

**Comment by arranfletcher** [comment]
> On Tue, Dec 31, 2019 at 09:26:31AM -0800, MF Softworks wrote: `rec -d -t raw -t wav -r 44100 -c 2 - | sudo ./pi_fm_adv --audio - --ps NygmaRadio --freq 103.9 --tp 0 --power 7`
> Please note that the program service name (ps) can carry only 8 characters.

Oh thanks I missed that part, I'll do a test this afternoon

**Comment by SimonSch** [comment]
Did you manage to get it to work?

**Comment by miegl** [comment]
Closing, open a new issue if needed.
