### ISSUE TITLE
 Raspberry 4 2GB Unfortunately there is only noise.

### ISSUE THREAD

**Issue by Klemy911** [miegl/PiFmAdv#70]
Hi my problem is that the program is installed and running. Unfortunately, at the frequency you specified, there is only a squeak and no sound. Someone already has a solution. Thanks

**Comment by flopyro** [comment]
have you tryed frequencies below 90MHz ?

**Comment by miegl** [comment]
Fixed by https://github.com/miegl/PiFmAdv/commit/9f4cbc32d9361527d3d5f40c18a9f1b8150dcfa2
