### ISSUE TITLE
Stream crashes after few seconds (as in #22)

### ISSUE THREAD

**Issue by MrBoombastic** [miegl/PiFmAdv#71]
Audio just stops playing without any errors. Using two RPi Zero's with Linux raspberrypi 4.19.97+ #1294 Thu Jan 30 13:10:54 GMT 2020 armv6l GNU/Linux.

**Comment by MrBoombastic** [comment]
Tried on this image: https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2019-07-12/, but this doesn't work. That's weird, because I was using this software and it was working fine! PiFmRds is working fine right now.

**Comment by miegl** [comment]
Does the audio stop playing or the entire signal cuts off?

**Comment by MrBoombastic** [comment]
Entire signal.

pon., 4 maj 2020, 19:52 użytkownik Josef Miegl <notifications@github.com>
napisał:

**Comment by miegl** [comment]
Could be due to low voltage detection. Do you have gpu_freq=250 in /boot/config.txt ?

**Comment by MrBoombastic** [comment]
It did the trick! Thank you!
