### ISSUE TITLE
Weird GPIO behaviour on raspberry pi 3b

### ISSUE THREAD

**Issue by crisdash96** [miegl/PiFmAdv#77]
l have a problem, l conect the antenna to the pines 3, 20, 32, only 32, is transmit, beacuse transmit very little, others pines whit antenna no transmit, I don't know why that happens.

**Comment by crisdash96** [comment]
Im buyed other raspberry (3b+) and works. Is for are a new raspberry. I have no solution for the raspberry 3b normal. Close this

**Comment by miegl** [comment]
Reopening as this should probably get fixed.

**Comment by crisdash96** [comment]
can you enable the gpio 21 to stream? It is the only one that works for me to transmit in the normal raspberry 3b

**Comment by crisdash96** [comment]
im sold the other raspberry with failed pins 8 and 20, beacuse no have solution.

**Comment by miegl** [comment]
Current version allows transmitting on all available GPCLK pins by setting `--gpio` and `--gpclk`.

**Comment by crisdash96** [comment]
The raspberry of months past have problems I’m devolved to the store, sorry raspberry it’s no my option for 4 months have a real fm transmitter 15 watts no problems and rds works witch 192khz sound card. 

Enviado desde mi iPhone
