### ISSUE TITLE
Crashes on pi3

### ISSUE THREAD

**Issue by Niall7459** [Miegl/PiFmAdv#9]
When I start the program it crashes my pi..

I cannot VNC or anything but it doesnt shutdown it just freezes.

**Comment by Niall7459** [comment]
Program loads and everything, I can hear the radio but cannot access pi.
This worked okay on mypi 2

**Comment by Niall7459** [comment]
I am using VNC but i also cannot FTP or SSH onto the pi in this state.

Will a apt-get dist-upgrade fix this....?

**Comment by Niall7459** [comment]
When i move a window while the TX is running it freeze.s

**Comment by Miegl** [comment]
Hm... weird. I don't have the Rpi 3 so I can't really test it, but maybe it's an issue with DMA channel?
You can try to apply this commit to PiFmAdv: https://github.com/SaucySoliton/PiFmRds/commit/fcfccdd0fe06c556f9b4e5776b516c1b9f5f2093

If the problem persists try running PiFmAdv on bare Arch Linux Arm (without xorg etc)

**Comment by Niall7459** [comment]
I run it headless now anyway

**Comment by Niall7459** [comment]
okay @meigl Is there a command I can use to apply this commit?

**Comment by Niall7459** [comment]
Never mind its only small

**Comment by Niall7459** [comment]
Do i have to MAKE?

**Comment by Niall7459** [comment]
OH MY YOU LEGEND IT WORKS GREAT THANK YOU THANK YOU THANK YOU THANK YOU NOW I CAN USE THE GUI!!!!!

Question : this doesnt affect performance using DMA 5?

**Comment by Miegl** [comment]
No, this doesn't affect performance.
I'll soon commit new update but I need to do some testing first.

**Comment by Niall7459** [comment]
Cool thanks it works great.
I'm now doing some cool testing with the fifo pipe.

Question: what is best antenna to use? homemade like a 1/2 wave dipole?

**Comment by Niall7459** [comment]
OH no problem My audio play slightly fast and cuts out after a few seconds!

**Comment by Niall7459** [comment]
Okay I have now set define DMA_NUMBER 6 And it seems to work okay

**Comment by Miegl** [comment]
well DMA channel 6 is reserved by GPU so idk how that will work out. You can try any of these channels which appears free: 4, 5, 8, 9, 10, 11, 12, 13, 14

**Comment by Niall7459** [comment]
oh lol 6 is working fine at the moment
