### ISSUE TITLE
PiFMAdv playing too slow and sine tone in background

### ISSUE THREAD

**Issue by ryanginn** [miegl/PiFmAdv#91]
Hi,
Code I'm using is:
sudo sox -t mp3 https://oneradio.cf/radio/8000/radio.mp3 -t wav - | sudo ./pi_fm_adv --freq 92.4 --ps ONERadio -rt 'All your favorite hits in one place! Listen Live: oneradio.cf' --ppm 1000000 --pty 9 --audio -

**Comment by ryanginn** [comment]
@miegl Any idea on what's wrong?

**Comment by miegl** [comment]
Possibly fixed in https://github.com/miegl/PiFmAdv/commit/9f4cbc32d9361527d3d5f40c18a9f1b8150dcfa2

**Comment by ryanginnelly252** [comment]
Hi, the sine tone is gone, but it still plays slow

**Comment by miegl** [comment]
Try getting rid of your `--ppm` setting. If that doesn't work, consider recording a sample of the output you are hearing. Thanks.

**Comment by ryanginnelly252** [comment]
Tried that. I'll send a recording below
https://voca.ro/1g6in4DMF016

**Comment by ryanginnelly252** [comment]
> Hi, Code I'm using is: sudo sox -t mp3 https://oneradio.cf/radio/8000/radio.mp3 -t wav - | sudo ./pi_fm_adv --freq 92.4 --ps ONERadio -rt 'All your favorite hits in one place! Listen Live: oneradio.cf' --ppm 1000000 --pty 9 --audio -

Just a heads up - I am just doing sudo ./pi_fm_rds --freq 92.4 --audio sound.wav

**Comment by ryanginnelly252** [comment]
Any update? @miegl

**Comment by miegl** [comment]
The projects binary should be named `pi_fm_adv`. Try running your Pi headless and experiment with `--pll a` and `--pll c`.
